<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="src\Extentions.fs" />
        <Compile Include="src\Types.fs" />
        <Compile Include="src\State.fs" />
        <Compile Include="src\View.fs" />
        <Compile Include="src\Main.fs" />
        <Content Include="index.html"/>
        <Content Include="public\favicon.ico" />
        <Content Include="public\main.css" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Fastoch" Version="0.13.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="Core\Core.fsproj" />
    </ItemGroup>
</Project>
