<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="src\Extentions.fs" />
        <Compile Include="src\App.fs"/>
        <Content Include="index.html"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Fastoch" Version="0.13.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="Core\Core.fsproj" />
    </ItemGroup>
</Project>
